#
# Copyright (c) 2018 Bosch Software Innovations GmbH and others
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

version: '3.7'

volumes:
  vhost:
  challange:
  certificates:

networks:
  proxy:
    driver: overlay

services:

  # ---------------------
  # nginx reverse proxy
  # ---------------------
  nginx:
    image: "jwilder/nginx-proxy"
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - certificates:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - challange:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  # ---------------------
  # lets encrypt nginx-proxy companion
  # ---------------------
  letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion"
    networks:
      - proxy
    volumes:
      - certificates:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - challange:/usr/share/nginx/html
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
