CREATE TABLE sp_auto_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at BIGINT,
    created_by VARCHAR(64),
    last_modified_at BIGINT,
    last_modified_by VARCHAR(64),
    optlock_revision BIGINT,
    tenant VARCHAR(40) NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512),
    query VARCHAR(1024) NOT NULL,
    distribution_set BIGINT NOT NULL,
    action_type INTEGER,
    weight INTEGER NOT NULL,
    confirmation_required BOOLEAN,
    start_at BIGINT,
    status INTEGER NOT NULL,
    approval_decided_by VARCHAR(64),
    approval_remark VARCHAR(255),
    access_control_context CLOB,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_auto_assignment ON sp_auto_assignment (name, tenant);
ALTER TABLE sp_auto_assignment
    ADD CONSTRAINT fk_auto_assignment_distribution_set FOREIGN KEY (distribution_set) REFERENCES sp_distribution_set (id) ON DELETE CASCADE;

INSERT INTO sp_auto_assignment (
    created_at, created_by, last_modified_at, last_modified_by, optlock_revision,
    tenant, name, query, distribution_set, action_type, weight,
    confirmation_required, start_at, status, access_control_context)
SELECT
    last_modified_at, auto_assign_initiated_by, last_modified_at, auto_assign_initiated_by, 0,
    tenant, name, query, auto_assign_distribution_set, auto_assign_action_type, auto_assign_weight,
    confirmation_required, last_modified_at, 4, access_control_context
FROM sp_target_filter_query
WHERE auto_assign_distribution_set IS NOT NULL;

ALTER TABLE sp_target_filter_query
    DROP CONSTRAINT fk_target_filter_query_auto_assign_distribution_set;
ALTER TABLE sp_target_filter_query
    DROP COLUMN auto_assign_distribution_set, auto_assign_action_type, auto_assign_weight,
        auto_assign_initiated_by, confirmation_required;