#
# Copyright (c) 2018 Bosch Software Innovations GmbH and others
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
version: '3.7'

include:
  - docker-compose-deps-mysql.yml

# EXPERIMENTAL!
services:

  # ---------------------
  # HawkBit DDI
  # ---------------------
  hawkbit-ddi:
    image: "hawkbit/hawkbit-ddi-server:latest-mysql"
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mariadb://mysql:3306/hawkbit'
      - 'SPRING_RABBITMQ_HOST=rabbitmq'
      - 'SPRING_RABBITMQ_USERNAME=guest'
      - 'SPRING_RABBITMQ_PASSWORD=guest'
      - 'SPRING_DATASOURCE_USERNAME=root'
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    labels:
      NAME: "hawkbit-ddi"

  # ---------------------
  # HawkBit DMF
  # ---------------------
  hawkbit-dmf:
    image: "hawkbit/hawkbit-dmf-server:latest-mysql"
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mariadb://mysql:3306/hawkbit'
      - 'SPRING_RABBITMQ_HOST=rabbitmq'
      - 'SPRING_RABBITMQ_USERNAME=guest'
      - 'SPRING_RABBITMQ_PASSWORD=guest'
      - 'SPRING_DATASOURCE_USERNAME=root'
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    labels:
      NAME: "hawkbit-dmf"

  # ---------------------
  # HawkBit MGMT
  # ---------------------
  hawkbit-mgmt:
    image: "hawkbit/hawkbit-mgmt-server:latest-mysql"
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mariadb://mysql:3306/hawkbit'
      - 'SPRING_RABBITMQ_HOST=rabbitmq'
      - 'SPRING_RABBITMQ_USERNAME=guest'
      - 'SPRING_RABBITMQ_PASSWORD=guest'
      - 'SPRING_DATASOURCE_USERNAME=root'
    volumes:
      - artifactrepo:/artifactrepo
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    labels:
      NAME: "hawkbit-mgmt"


#  # ---------------------
#  # HawkBit Vaadin 8 based UI (NOT SUPPORTED!)
#  # Outdated and not supported - may not work or lead to problems.
#  # NOT Recommended - use it only AT YOUR RISK!
#  # ---------------------
#  hawkbit-vv8ui:
#    image: "hawkbit/hawkbit-vv8-ui:latest-mysql"
#    environment:
#      - 'SPRING_DATASOURCE_URL=jdbc:mariadb://mysql:3306/hawkbit'
#      - 'SPRING_RABBITMQ_HOST=rabbitmq'
#      - 'SPRING_RABBITMQ_USERNAME=guest'
#      - 'SPRING_RABBITMQ_PASSWORD=guest'
#      - 'SPRING_DATASOURCE_USERNAME=root'
#    volumes:
#      - artifactrepo:/artifactrepo
#    restart: always
#    ports:
#      - "8082:8082"
#    depends_on:
#      mysql:
#        condition: service_healthy
#    labels:
#      NAME: "hawkbit-vv8-ui"

volumes:
  artifactrepo:
    driver: local
