name: Unset Git Config

on:
  # enable running the workflow manually
  workflow_dispatch:

jobs:
  unset-git-config:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK & Maven Central credentials
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Check dependency licenses with dash tool
        run: |
              git config --local --unset user.name
              git config --local --unset user.email
              git config --global --unset user.name
              git config --global --unset user.email
