name: Verify (PostgreSQL)

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.3rd-party/**'
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - '.3rd-party/**'
      - 'docs/**'
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify-postgresql:
    uses: ./.github/workflows/reusable_workflow_verify.yaml
    with:
      repository: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name || github.repository }}
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
      maven_properties: '-Dspring.jpa.database=POSTGRESQL -Dspring.datasource.url=jdbc:postgresql://localhost:5432/hawkbit -Dspring.datasource.username=postgres -Dspring.datasource.password=admin'
